version: '3.8'

services:
  app:
    build: .
    container_name: test_app
    environment:
      - PORT=3000
      - INSTANCE_ID=1
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/src/logs
    restart: unless-stopped
